# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#test-discovery

name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: dependencies
      run: |
        python -mpip install --user --no-cache-dir --upgrade -r requirements.txt
    - name: test
      env:
        APP_ID: ${{ secrets.APP_ID }}
        SECRET: ${{ secrets.SECRET }}
        SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
      run: |
        python proto.py
